In [5]:
import numpy as np
from astropy.io import fits

image = np.ones((4,3))

print(image)

fits.writeto(data=image, filename='test_Data/4x3_ones.fits')


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [8]:
from LensData.ImageTools import *

dir = '/home/jammy/PycharmProjects/AutoLens/Input_Data/'

load_fits(dir+'slacs_3_post.fits', hdu=1)

SyntaxError: invalid syntax (ImageTools.py, line 19)

In [22]:
import numpy as np

image = np.zeros((4,3))

image[0, 0] = 1 
image[0, 1] = 2
image[0, 2] = 3
image[1, 0] = 4
image[1, 1] = 100 # Not on edge
image[1, 2] = 5
image[2, 0] = 6
image[2, 1] = 100 # Not on edge
image[2, 2] = 7
image[3, 0] = 8
image[3, 1] = 9
image[3, 2] = 10

print(image)


[[   1.    2.    3.]
 [   4.  100.    5.]
 [   6.  100.    7.]
 [   8.    9.   10.]]


In [30]:
from scipy.stats import norm

mu, sigma = norm.fit(np.array([1,2,3,4,5,6,7,8,9,10,11,12]))
print(mu, sigma)

6.5 3.45205252953
